// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
      env("ENVIROMENT") === "dev"
        ? env("DEV_DATABASE_URL")
        : env("PROD_DATABASE_URL"),
  },
});
console.log(
  "urls: ",
  "dev: ",
  env("DEV_DATABASE_URL"),
  "prod: ",
  env("PROD_DATABASE_URL"),
  "env: ",
  env("ENVIROMENT"),
);
